### ISSUE TITLE
inverted condition in if

### ISSUE THREAD

**Issue by sdecalom** [pe7er/mod_db8sitelastmodified#2]
Hello Peter Martin,

Thank you for your module. It's a useful  module. I would like to inform an error.
In abstract class modDb8SiteLastModifiedHelper

you have inverted the condition in if

if ( $datedisplay == 1 ){
    $displaydate = $result->modified;
}elseif( $datedisplay == 2 ){
    $displaydate = $result->created;
}else{
    $displaydate = max($result->modified, $result->created);
}

You must to replace it by this

if ( $datedisplay == 2 ){
    $displaydate = $result->modified;
}elseif( $datedisplay == 1 ){
    $displaydate = $result->created;
}else{
    $displaydate = max($result->modified, $result->created);
}

**Comment by pe7er** [comment]
Thanks!
